# Form implementation generated from reading ui file 'src/ui/create_db_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewFileDialog:
    def setupUi(self, NewFileDialog):
        NewFileDialog.setObjectName("NewFileDialog")
        NewFileDialog.resize(520, 262)
        self.label_2 = QtWidgets.QLabel(parent=NewFileDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 171, 41))
        self.label_2.setObjectName("label_2")
        self.okButton = QtWidgets.QPushButton(parent=NewFileDialog)
        self.okButton.setGeometry(QtCore.QRect(300, 210, 93, 28))
        self.okButton.setObjectName("okButton")
        self.label = QtWidgets.QLabel(parent=NewFileDialog)
        self.label.setGeometry(QtCore.QRect(20, 140, 171, 41))
        self.label.setObjectName("label")
        self.passwordLine = QtWidgets.QLineEdit(parent=NewFileDialog)
        self.passwordLine.setGeometry(QtCore.QRect(140, 150, 361, 31))
        self.passwordLine.setText("")
        self.passwordLine.setObjectName("passwordLine")
        self.pathLine = QtWidgets.QLabel(parent=NewFileDialog)
        self.pathLine.setGeometry(QtCore.QRect(20, 60, 471, 41))
        self.pathLine.setObjectName("pathLine")
        self.cancelButton = QtWidgets.QPushButton(parent=NewFileDialog)
        self.cancelButton.setGeometry(QtCore.QRect(410, 210, 93, 28))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(NewFileDialog)
        QtCore.QMetaObject.connectSlotsByName(NewFileDialog)

    def retranslateUi(self, NewFileDialog):
        _translate = QtCore.QCoreApplication.translate
        NewFileDialog.setWindowTitle(_translate("NewFileDialog", "Dialog"))
        self.label_2.setText(_translate("NewFileDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Create Master key</span></p></body></html>"))
        self.okButton.setText(_translate("NewFileDialog", "Enter"))
        self.label.setText(_translate("NewFileDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Master key:</span></p></body></html>"))
        self.passwordLine.setToolTip(_translate("NewFileDialog", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.passwordLine.setWhatsThis(_translate("NewFileDialog", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.pathLine.setText(_translate("NewFileDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">None</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.cancelButton.setText(_translate("NewFileDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewFileDialog = QtWidgets.QDialog()
    ui = Ui_NewFileDialog()
    ui.setupUi(NewFileDialog)
    NewFileDialog.show()
    sys.exit(app.exec())
