# Form implementation generated from reading ui file 'src/ui/new_entry.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addNewEntry(object):
    def setupUi(self, addNewEntry):
        addNewEntry.setObjectName("addNewEntry")
        addNewEntry.resize(534, 350)
        self.titleLabel = QtWidgets.QLabel(parent=addNewEntry)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 161, 51))
        self.titleLabel.setObjectName("titleLabel")
        self.usernameLable = QtWidgets.QLabel(parent=addNewEntry)
        self.usernameLable.setGeometry(QtCore.QRect(10, 40, 161, 51))
        self.usernameLable.setObjectName("usernameLable")
        self.passwordLabel = QtWidgets.QLabel(parent=addNewEntry)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 100, 161, 41))
        self.passwordLabel.setObjectName("passwordLabel")
        self.linkLabel = QtWidgets.QLabel(parent=addNewEntry)
        self.linkLabel.setGeometry(QtCore.QRect(10, 150, 161, 51))
        self.linkLabel.setObjectName("linkLabel")
        self.notesLabel = QtWidgets.QLabel(parent=addNewEntry)
        self.notesLabel.setGeometry(QtCore.QRect(10, 180, 161, 51))
        self.notesLabel.setObjectName("notesLabel")
        self.titleLine = QtWidgets.QLineEdit(parent=addNewEntry)
        self.titleLine.setGeometry(QtCore.QRect(150, 10, 361, 31))
        self.titleLine.setText("")
        self.titleLine.setObjectName("titleLine")
        self.usernameLine = QtWidgets.QLineEdit(parent=addNewEntry)
        self.usernameLine.setGeometry(QtCore.QRect(150, 50, 361, 31))
        self.usernameLine.setText("")
        self.usernameLine.setObjectName("usernameLine")
        self.linkLine = QtWidgets.QLineEdit(parent=addNewEntry)
        self.linkLine.setGeometry(QtCore.QRect(150, 150, 361, 31))
        self.linkLine.setText("")
        self.linkLine.setObjectName("linkLine")
        self.passwordLine = QtWidgets.QLineEdit(parent=addNewEntry)
        self.passwordLine.setGeometry(QtCore.QRect(150, 100, 361, 31))
        self.passwordLine.setText("")
        self.passwordLine.setObjectName("passwordLine")
        self.notesLine = QtWidgets.QLineEdit(parent=addNewEntry)
        self.notesLine.setGeometry(QtCore.QRect(150, 190, 361, 111))
        self.notesLine.setText("")
        self.notesLine.setObjectName("notesLine")
        self.addButton = QtWidgets.QPushButton(parent=addNewEntry)
        self.addButton.setGeometry(QtCore.QRect(420, 310, 93, 28))
        self.addButton.setObjectName("addButton")
        self.cancelButton = QtWidgets.QPushButton(parent=addNewEntry)
        self.cancelButton.setGeometry(QtCore.QRect(310, 310, 93, 28))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(addNewEntry)
        QtCore.QMetaObject.connectSlotsByName(addNewEntry)

    def retranslateUi(self, addNewEntry):
        _translate = QtCore.QCoreApplication.translate
        addNewEntry.setWindowTitle(_translate("addNewEntry", "Dialog"))
        self.titleLabel.setText(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:12pt;\">Title</span></p></body></html>"))
        self.usernameLable.setText(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.passwordLabel.setText(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p><p><br/></p></body></html>"))
        self.linkLabel.setText(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:12pt;\">Link</span></p><p><br/></p></body></html>"))
        self.notesLabel.setText(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:12pt;\">Notes</span></p></body></html>"))
        self.titleLine.setToolTip(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.titleLine.setWhatsThis(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.usernameLine.setToolTip(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.usernameLine.setWhatsThis(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.linkLine.setToolTip(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.linkLine.setWhatsThis(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.passwordLine.setToolTip(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.passwordLine.setWhatsThis(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.notesLine.setToolTip(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.notesLine.setWhatsThis(_translate("addNewEntry", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.addButton.setText(_translate("addNewEntry", "Add"))
        self.cancelButton.setText(_translate("addNewEntry", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addNewEntry = QtWidgets.QDialog()
    ui = Ui_addNewEntry()
    ui.setupUi(addNewEntry)
    addNewEntry.show()
    sys.exit(app.exec())
