# Form implementation generated from reading ui file 'src/ui/open_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogUI(object):
    def setupUi(self, DialogUI):
        DialogUI.setObjectName("DialogUI")
        DialogUI.resize(508, 247)
        self.passwordLine = QtWidgets.QLineEdit(parent=DialogUI)
        self.passwordLine.setGeometry(QtCore.QRect(130, 140, 361, 31))
        self.passwordLine.setText("")
        self.passwordLine.setObjectName("passwordLine")
        self.helpButton = QtWidgets.QPushButton(parent=DialogUI)
        self.helpButton.setGeometry(QtCore.QRect(10, 200, 93, 28))
        self.helpButton.setObjectName("helpButton")
        self.okButton = QtWidgets.QPushButton(parent=DialogUI)
        self.okButton.setGeometry(QtCore.QRect(290, 200, 93, 28))
        self.okButton.setObjectName("okButton")
        self.buttonGroup = QtWidgets.QButtonGroup(DialogUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=DialogUI)
        self.cancelButton.setGeometry(QtCore.QRect(400, 200, 93, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonGroup.addButton(self.cancelButton)
        self.label = QtWidgets.QLabel(parent=DialogUI)
        self.label.setGeometry(QtCore.QRect(10, 130, 171, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=DialogUI)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 41))
        self.label_2.setObjectName("label_2")
        self.pathLine = QtWidgets.QLabel(parent=DialogUI)
        self.pathLine.setGeometry(QtCore.QRect(10, 50, 471, 41))
        self.pathLine.setObjectName("pathLine")
        self.label_3 = QtWidgets.QLabel(parent=DialogUI)
        self.label_3.setGeometry(QtCore.QRect(490, 0, 171, 41))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DialogUI)
        QtCore.QMetaObject.connectSlotsByName(DialogUI)

    def retranslateUi(self, DialogUI):
        _translate = QtCore.QCoreApplication.translate
        DialogUI.setWindowTitle(_translate("DialogUI", "Dialog"))
        self.passwordLine.setToolTip(_translate("DialogUI", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.passwordLine.setWhatsThis(_translate("DialogUI", "<html><head/><body><p><span style=\" font-size:11pt;\">master password here</span></p></body></html>"))
        self.helpButton.setText(_translate("DialogUI", "Help"))
        self.okButton.setText(_translate("DialogUI", "Enter"))
        self.cancelButton.setText(_translate("DialogUI", "Cancel"))
        self.label.setText(_translate("DialogUI", "<html><head/><body><p><span style=\" font-size:12pt;\">Master key:</span></p></body></html>"))
        self.label_2.setText(_translate("DialogUI", "<html><head/><body><p><span style=\" font-size:12pt;\">Enter Master key</span></p></body></html>"))
        self.pathLine.setText(_translate("DialogUI", "<html><head/><body><p><span style=\" font-size:10pt;\">None</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_3.setText(_translate("DialogUI", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogUI = QtWidgets.QDialog()
    ui = Ui_DialogUI()
    ui.setupUi(DialogUI)
    DialogUI.show()
    sys.exit(app.exec())
